# Generated by Django 4.2 on 2023-12-06 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_multijob_work"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="work",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.work",
            ),
        ),
    ]
