# Generated by Django 4.2 on 2023-12-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_job_work"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="type",
        ),
        migrations.RemoveField(
            model_name="vehicleprofile",
            name="type",
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[("pp", "pickup"), ("dd", "delivery")],
                default="pp",
                max_length=2,
            ),
        ),
        migrations.DeleteModel(
            name="VehicleType",
        ),
    ]
