# Generated by Django 4.2 on 2024-04-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_category_solution_freshnesspenalty_job_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('-created_at',)},
        ),
    ]
