# Generated by Django 4.2 on 2025-09-09 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_alter_work_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicleprofile',
            name='max_capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vehicleprofile',
            name='temperature',
            field=models.CharField(choices=[('ambient', 'Ambient'), ('refrigerated', 'Refrigerated')], default='ambient', max_length=16),
        ),
        migrations.AddField(
            model_name='vehicleprofile',
            name='truck_type',
            field=models.CharField(choices=[('rigid_3_5_7_5', 'Rigid (>3.5–7.5 t)'), ('rigid_7_5_17', 'Rigid (>7.5–17 t)'), ('rigid_17_plus', 'Rigid (>17 t)'), ('artic_3_5_33', 'Articulated (>3.5–33 t)'), ('artic_33_plus', 'Articulated (>33 t)')], default='rigid_7_5_17', max_length=32),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='vehicleprofile',
            unique_together={('name', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='work',
            unique_together={('name', 'created_by')},
        ),
    ]
