from django.urls import path

from . import views, rest_views

urlpatterns = [
    path('works/', rest_views.get_work, name="work-get"),
    path('last_solution/', rest_views.previous_solution_get, name="last-solution-get"),
    path('export_solution_csv/<int:pk>/', rest_views.export_solution_csv,
         name="export_solution_csv"),
    path('emission_report/<int:pk>/', rest_views.emission_estimation,
         name="emission_solution"),
    path('categories/', rest_views.category_get, name="categories-get"),
    path('category_delete/<int:pk>/', rest_views.category_delete, name="categories-delete"),
    path('category_update/<int:pk>/', rest_views.category_update, name="categories-update"),
    path('search-works/', rest_views.get_search_work, name="search-work-get"),
    path('solve/<int:pk>', rest_views.solve, name="work-solve"),
    path('work-create/', rest_views.work_post, name="work-post"),
    path('category_create/', rest_views.category_create, name="category-create"),
    path('work-update/<int:pk>/', rest_views.work_put, name='work_put'),
    path('work_delete/<int:pk>/', rest_views.delete_work, name="work-delete"),
    path('job-create/', rest_views.job_post, name='job-create'),
    path('job-create-bulk/', rest_views.bulk_job_create, name='job-create-bulk'),
    path('fleet-create-bulk/', rest_views.bulk_fleet_create, name='fleet-create-bulk'),
    path('job-delete/<int:pk>/', rest_views.job_delete, name='job-delete'),
    path('job-update/<int:pk>/', rest_views.job_put, name='job_put'),
    path('update-vehicle/<int:pk>/', rest_views.vehicle_put, name='vehicle_put'),
    path('jobs/', rest_views.job_get, name='job-get'),
    path('multijob-create/', rest_views.multi_job_post, name='multijob-create'),
    path('vehicles/', rest_views.vehicle_get, name='vehicle-get'),
    path('vehicle-create/', rest_views.vehicle_bulk_post, name='vehicle-create'),
    path('vehicle-delete/<int:pk>/', rest_views.vehicle_delete, name="vehicle-delete"),
    path('vehicle-profile-create/', rest_views.vehicle_profile_post,
         name='vehicle-profile-create'),
    path('vehicle-profile-update/<int:pk>/', rest_views.vehicle_profile_update,
         name='vehicle-profile-update'),
    path('vehicle-profile-delete/<int:pk>/', rest_views.delete_vehicle_profile,
         name="vehicle-profile-delete"),
    path('vehicle-profiles/', rest_views.vehicle_profile_get, name='vehicle-profile-get'),
    path("vehicle-profiles-search/", rest_views.search_vehicle_profile,
         name="search-vehicle-profile"),

    path('', views.work, name="home"),
    # path('job/', views.job, name='job'),
    # path('multijob/', views.multi_job, name='multijob'),
    # path('vehicle/', views.vehicle, name='vehicle'),
    # path('solution/<int:pk>', views.solution, name='solution'),
    # path('solution/<int:pk>/solve', views.solve, name='solve'),
]
